### ISSUE TITLE
fix when I create a client with no client authentication , the API create a service account

### ISSUE THREAD

**Issue by NathaelB** [ferriskey/ferriskey#191]
### Bug Description

When I create a client with the following fields , the API create a service-account

```yaml
{
    "clientId": "test2",
    "name": "test2",
    "enabled": true,
    "protocol": "openid-connect",
    "clientAuthentication": false,
    "client_id": "test2",
    "client_type": "public",
    "public_client": true
}
```

But it should not create a service account

### To Reproduce

1. Go to Portail UI
2. Create a Client without client authentication
3. Go to show the users

### Environment

- OS:
- Browser:
- Version:
